plugins {
    id 'application'
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1' // Версия должна соответствовать вашему Gradle 8.x
}

dependencies {
    implementation project(':common')
}

application {
    mainClass = 'Main'
}
// Удалите кастомный блок jar { manifest { ... } }, Shadow сделает это сам